const item = (name, amount) => ({ item: name, amount, isLeftover: false });

export const INITIAL_POST_PREFIX = 'initial-';

export const initialPosts = [
  {
    id: 'initial-crispy-chicken-tomato-sauce',
    title: 'Crispy Chicken with Homemade Tomato Sauce',
    image: '/chiklen_tight.jpg',
    description:
      'Golden, crunchy chicken thighs with juicy meat inside, served over a rich tomato sauce simmered slowly with garlic and herbs. Comfort food that is just as good with rice, mashed potatoes or crusty bread.',
    tags: ['chicken', 'tomato', 'garlic', 'onion', 'flour', 'dinner'],
    ingredients: [
      item('chicken', '4 thighs'),
      item('flour', '1/2 cup'),
      item('egg', '1'),
      item('tomato', '500 g'),
      item('garlic', '3 cloves'),
      item('onion', '1'),
      item('olive oil', '3 tbsp'),
      item('salt and pepper', 'to taste'),
    ],
    steps: [
      'Season the chicken with salt and pepper, dip in beaten egg, then coat in flour.',
      'Fry in hot oil for 6-8 minutes per side until golden, crisp and cooked through. Drain on paper towels.',
      'Sauté chopped onion and garlic in olive oil until soft.',
      'Add chopped tomatoes, season, and simmer for 20 minutes until thick and rich.',
      'Serve the chicken on top of or next to the warm tomato sauce.',
    ],
    leftoverIngredients: [],
    authorId: 'greenbite',
    published: true,
    likes: [],
  },
  {
    id: 'initial-spicy-thai-style-noodles',
    title: 'Spicy Thai-Style Noodles',
    image: '/thai_noodle.jpg',
    description:
      'Chewy noodles tossed with tender chicken, crisp vegetables and a fragrant, spicy sauce of garlic, chili and soy. Ready in about 20 minutes and full of fresh, bold flavour.',
    tags: ['noodles', 'chicken', 'chili', 'garlic', 'carrot', 'spicy'],
    ingredients: [
      item('noodles', '250 g'),
      item('chicken', '300 g'),
      item('carrot', '1'),
      item('bell pepper', '1'),
      item('garlic', '3 cloves'),
      item('chili', '1-2'),
      item('soy sauce', '3 tbsp'),
      item('lime', '1'),
      item('spring onion', '2'),
    ],
    steps: [
      'Cook the noodles according to the package, drain and set aside.',
      'Slice the chicken thinly and stir-fry in a hot pan until cooked through.',
      'Add garlic, chili, carrot and bell pepper and stir-fry for 3-4 minutes.',
      'Add the noodles and soy sauce and toss everything together over high heat.',
      'Finish with a squeeze of lime and sliced spring onion.',
    ],
    leftoverIngredients: [],
    authorId: 'greenbite',
    published: true,
    likes: [],
  },
  {
    id: 'initial-creamy-tomato-beef-pasta',
    title: 'Creamy Tomato & Beef Pasta',
    image: '/pasta.jpg',
    description:
      'Tender pasta in a silky tomato sauce with savoury ground beef. Hearty, comforting and easy enough for a weeknight dinner the whole family will enjoy.',
    tags: ['pasta', 'beef', 'tomato', 'onion', 'garlic', 'cheese'],
    ingredients: [
      item('pasta', '300 g'),
      item('beef', '300 g'),
      item('tomato', '400 g'),
      item('onion', '1'),
      item('garlic', '2 cloves'),
      item('cream', '100 ml'),
      item('cheese', '40 g'),
      item('olive oil', '2 tbsp'),
    ],
    steps: [
      'Boil the pasta in salted water until al dente, then drain.',
      'Brown the ground beef with chopped onion and garlic in olive oil.',
      'Add the tomatoes, season, and simmer for 15 minutes.',
      'Stir in the cream and heat through until the sauce is smooth.',
      'Toss with the pasta and top with grated cheese.',
    ],
    leftoverIngredients: [],
    authorId: 'greenbite',
    published: true,
    likes: [],
  },
  {
    id: 'initial-juicy-seasoned-ground-beef',
    title: 'Juicy Seasoned Ground Beef Bites',
    image: '/grounded_beef.jpg',
    description:
      'Ground beef seasoned with garlic, onion and herbs, shaped into compact bites and seared until browned outside and juicy inside. A simple, protein-rich main that works with rice, salad or vegetables.',
    tags: ['beef', 'garlic', 'onion', 'egg', 'dinner'],
    ingredients: [
      item('beef', '500 g'),
      item('onion', '1/2'),
      item('garlic', '2 cloves'),
      item('egg', '1'),
      item('breadcrumbs', '3 tbsp'),
      item('salt and pepper', 'to taste'),
      item('herbs', '1 tsp'),
    ],
    steps: [
      'Mix the ground beef with finely chopped onion, garlic, egg, breadcrumbs, herbs, salt and pepper.',
      'Shape the mixture into compact, evenly sized portions.',
      'Sear in a hot pan for 3-4 minutes per side until deeply browned.',
      'Lower the heat, cover and cook for a few more minutes until cooked through.',
      'Rest briefly before serving.',
    ],
    leftoverIngredients: [],
    authorId: 'greenbite',
    published: true,
    likes: [],
  },
  {
    id: 'initial-crispy-chicken-strawberry-sauce',
    title: 'Crispy Fried Chicken with Sweet Strawberry Sauce',
    image: '/boned_chiken.jpg',
    description:
      'Crunchy boneless fried chicken with a glossy sweet strawberry glaze that adds a fruity, slightly tangy contrast to the salty crust. A fun, vibrant dish that is great for sharing.',
    tags: ['chicken', 'strawberry', 'flour', 'egg', 'garlic', 'sweet'],
    ingredients: [
      item('chicken', '500 g'),
      item('flour', '1/2 cup'),
      item('egg', '1'),
      item('strawberry', '200 g'),
      item('sugar', '2 tbsp'),
      item('garlic', '1 clove'),
      item('vinegar', '1 tbsp'),
      item('oil', 'for frying'),
    ],
    steps: [
      'Cut the chicken into pieces, season, dip in beaten egg and coat with flour.',
      'Fry in hot oil until golden and crisp, then drain.',
      'Simmer chopped strawberries with sugar, garlic and vinegar for 8-10 minutes until thick and glossy.',
      'Coat the chicken in the strawberry sauce or serve it on the side.',
    ],
    leftoverIngredients: [],
    authorId: 'greenbite',
    published: true,
    likes: [],
  },
];
